itemId=677c278be95006a69a3c59a9
### Get All Inventory Items
GET http://localhost:3000/api/inventory
Content-Type: application/json

###

### Add a New Inventory Item
POST http://localhost:3000/api/inventory
Content-Type: application/json

{
    "name": "Laptop",
    "quantity": 10
}

###

### Update an Inventory Item
PUT http://localhost:3000/api/inventory/{{itemId}}
Content-Type: application/json

{
    "quantity": 15
}

###

### Delete an Inventory Item
DELETE http://localhost:3000/api/inventory/{{itemId}}